export interface CurrencyDetails {
  id: string,
  name: string,
  symbol: string,
  rank: number,
  is_new: boolean,
  is_active: boolean,
  type: string,
  logo: string,
  description: string,
  message: string,
  open_source: boolean,
  started_at: string,
  development_status: string,
  hardware_wallet: true,
  first_data_at: string,
  last_data_at: string,
  links: object,
}
